### PR TITLE
menu

### PR DESCRIPTION
**Pull request by soniaCastillo**
structure page

### CODE REVIEW

**Comment by soniaCastillo** [comment]
xcd

**Comment by soniaCastillo** [comment]
yes

**Comment by Qianwen-Pan** [comment]
> yes

**Review by Qianwen-Pan — COMMENTED** [review]
approved

**Comment by Qianwen-Pan** [comment]
@soniaCastillo Approved. Please address the conflict above so that it can be merged. Thanks. You can pull the latest change from the repo and regenerate `package-lock.json` file by running `npm -i`.

**Pull request merged**
